export const productsData = [
  {
    name: "Áo khoác da nam",
    category: "Thời trang nam",
    brand: "Zara",
    price: 89.99,
    description: "Áo khoác da nam thời trang từ Zara.",
    imageURL: "https://example.com/product1.jpg",
    rating: 4.5,
    stock: 50,
    color: "Đen",
    size: "M",
  },
  {
    name: "Váy maxi hoa",
    category: "Thời trang nữ",
    brand: "H&M",
    price: 59.99,
    description: "Váy maxi hoa dễ thương từ H&M.",
    imageURL: "https://example.com/product2.jpg",
    rating: 4.2,
    stock: 40,
    color: "Xanh lá cây",
    size: "S",
  },
  {
    name: "Quần bò nam",
    category: "Thời trang nam",
    brand: "Levi's",
    price: 69.99,
    description: "Quần bò nam phong cách từ Levi's.",
    imageURL: "https://example.com/product3.jpg",
    rating: 4.3,
    stock: 60,
    color: "Xanh đậm",
    size: "L",
  },
  {
    name: "Áo len nữ",
    category: "Thời trang nữ",
    brand: "Gap",
    price: 49.99,
    description: "Áo len nữ ấm áp từ Gap.",
    imageURL: "https://example.com/product4.jpg",
    rating: 4.0,
    stock: 55,
    color: "Hồng",
    size: "M",
  },
  {
    name: "Giày thể thao nam",
    category: "Thời trang nam",
    brand: "Nike",
    price: 79.99,
    description: "Giày thể thao nam từ Nike.",
    imageURL: "https://example.com/product5.jpg",
    rating: 4.6,
    stock: 45,
    color: "Trắng",
    size: "XL",
  },
  {
    name: "Đầm dự tiệc",
    category: "Thời trang nữ",
    brand: "ASOS",
    price: 99.99,
    description: "Đầm dự tiệc lộng lẫy từ ASOS.",
    imageURL: "https://example.com/product6.jpg",
    rating: 4.4,
    stock: 30,
    color: "Vàng",
    size: "L",
  },
  {
    name: "Balo học sinh",
    category: "Thời trang phụ kiện",
    brand: "JanSport",
    price: 29.99,
    description: "Balo học sinh thời trang từ JanSport.",
    imageURL: "https://example.com/product7.jpg",
    rating: 4.7,
    stock: 70,
    color: "Xanh dương",
    size: "One Size",
  },
  {
    name: "Áo len nam",
    category: "Thời trang nam",
    brand: "Uniqlo",
    price: 39.99,
    description: "Áo len nam ấm áp từ Uniqlo.",
    imageURL: "https://example.com/product8.jpg",
    rating: 4.2,
    stock: 65,
    color: "Xám",
    size: "S",
  },
  {
    name: "Áo sơ mi nữ",
    category: "Thời trang nữ",
    brand: "Mango",
    price: 44.99,
    description: "Áo sơ mi nữ dễ thương từ Mango.",
    imageURL: "https://example.com/product9.jpg",
    rating: 4.3,
    stock: 50,
    color: "Trắng",
    size: "M",
  },
  {
    name: "Giày cao gót nữ",
    category: "Thời trang nữ",
    brand: "Steve Madden",
    price: 69.99,
    description: "Giày cao gót nữ thời trang từ Steve Madden.",
    imageURL: "https://example.com/product10.jpg",
    rating: 4.8,
    stock: 35,
    color: "Đen",
    size: "L",
  },
];
